- name: Gather all facts first
  hosts: adcs
  gather_facts: yes
  tasks: [ ]

- name: Docker Playbook
  hosts: adcs
  become: true
  vars:
  serial:
    - 1
    - "100%"
  max_fail_percentage: 0
  tasks:
    - name: Use Administrator password
      fail:
        msg: "You must define the 'administrator_password' variable, e.g. -e administrator_password='P@ssw0rd'"
      when: administrator_password is not defined
      failed_when: administrator_password is not defined

    - name: Create /etc/hosts
      blockinfile:
        block: |
          {% for host in ansible_play_hosts_all %}
          {% if 'ansible_default_ipv4' in hostvars[host] and 'address' in hostvars[host]['ansible_default_ipv4']  %}
          {{ hostvars[host]['ansible_default_ipv4']['address'] }}  {{ host }}
          {{ hostvars[host]['ansible_default_ipv4']['address'] }}  {{ hostvars[host]['inventory_hostname_short'] }}
          {{ hostvars[host]['ansible_default_ipv4']['address'] }}  {{ hostvars[host]['inventory_hostname_short'] }}.ad.zam.haus
          {{ hostvars[host]['ansible_default_ipv4']['address'] }}  ad.zam.haus
          {% endif %}
          {% endfor %}
        path: /etc/hosts
        create: yes
        append_newline: yes
        prepend_newline: yes
      when: "'docker' not in group_names"

    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install packages
      apt:
        pkg:
          - samba-ad-dc
          - samba-ad-provision
          #- libpam-heimdal
          - heimdal-clients
          - ldb-tools
          - winbind
          #- libpam-winbind
          - smbclient
          - libnss-winbind
          #- bind9
          #- bind9utils
          - nano
          - tmux
          - curl
          - rsync
          - iproute2
          - inetutils-ping
          - mtr
          - tree
          - less
          - dnsutils
          - python3-dnspython

    - name: Stop conflicting services
      service:
        name: "{{ item }}"
        state: stopped
        enabled: no
      loop:
        - smbd
        - nmbd
        - winbind
        - samba-ad-dc

    - name: Maintain uv
      when: false
      block:
        - name: Check if uv exists in PATH
          shell: "which uv"
          ignore_errors: true
          register: uv_which_out
        - name: Upgrade uv
          when: uv_which_out.rc == 0
          shell: "uv self update"
        - name: Install uv
          when: uv_which_out.rc != 0
          shell: "curl -LsSf https://astral.sh/uv/install.sh | UV_INSTALL_DIR='/usr/local/bin' sh"

    - name: Install first ADC
      when: ansible_play_hosts_all[0] == inventory_hostname
      block:
        - name: Check if domain is already provisioned
          check_mode: yes
          ansible.builtin.lineinfile:
            path: /etc/samba/smb.conf
            regexp: "^\\s*server role\\s*=\\s*active directory domain controller\\s*$"
            state: absent
          register: domain_provisioned_check
          changed_when: false
        - name: Status
          debug:
            msg: |
              Domain already provisioned = {{ (domain_provisioned_check.found | default(0)) > 0 }}
        - name: Provision the domain if not already done
          when: (force_reinstall | default(false) | bool) or (domain_provisioned_check.found | default(0)) == 0
          block:
            - name: Delete smb.conf
              shell: rm -f /etc/samba/smb.conf
            - name: Provision
              shell: |
                timeout 300 \
                samba-tool domain provision \
                --domain AD \
                --server-role dc \
                --dns-backend SAMBA_INTERNAL \
                --realm ad.zam.haus \
                --adminpass {{ administrator_password|quote }}
              register: provision_out
              ignore_errors: true
            - name: Debug provision output
              debug:
                msg: |
                  stdout:
                  {{ provision_out.stdout }}
                  ====
                  stderr:
                  {{ provision_out.stderr }}
            - name: Fail if provision failed
              fail:
                msg: "Provisioning the domain failed. See previous output."
              when: provision_out.rc != 0
            - name: Install kerberos config
              copy:
                src: /var/lib/samba/private/krb5.conf
                dest: /etc/krb5.conf
                remote_src: yes
                force: yes
            - name: Start Samba-Ad-Dc Service
              service:
                name: samba-ad-dc
                state: started
            - name: Wait for Samba-Ad-Dc Service to be started
              wait_for:
                port: 389
                state: started
                delay: 0
                timeout: 5
            - name: Get domain info
              shell: "samba-tool domain info 127.0.0.1"
              register: domain_info_out
              ignore_errors: true
            - name: Debug domain info output
              debug:
                msg: |
                  stdout:
                  {{ domain_info_out.stdout }}
                  ====
                  stderr:
                  {{ domain_info_out.stderr }}
            - name: Fail if domain info failed
              fail:
                msg: "Getting domain info failed. See previous output."
              when: domain_info_out.rc != 0
            - name: Add dns record for <hostname>.ad.zam.haus
              when: "'docker' not in group_names"
              shell: |
                samba-tool dns add -U='AD\Administrator' --password={{ administrator_password|quote }} ad001.srv.zam.haus ad.zam.haus {{ inventory_hostname_short | quote }}.ad.zam.haus A {{ ansible_default_ipv4.address | quote }}
              register: add_dns_out
              changed_when: add_dns_out.rc == 0
              failed_when: add_dns_out.rc != 0 and ('WERR_DNS_ERROR_RECORD_ALREADY_EXISTS' not in add_dns_out.stderr)
            - name: Restart Samba-Ad-Dc Service
              service:
                name: samba-ad-dc
                state: restarted
            - name: Wait for Samba-Ad-Dc Service to be started
              wait_for:
                port: 389
                state: started
                delay: 0
                timeout: 5

    - name: Join additional DCs
      when: ansible_play_hosts_all[0] != inventory_hostname
      block:
        - name: Check if domain is already provisioned
          check_mode: yes
          ansible.builtin.lineinfile:
            path: /etc/samba/smb.conf
            regexp: "^\\s*server role\\s*=\\s*active directory domain controller\\s*$"
            state: absent
          register: domain_provisioned_check
          changed_when: false
        - name: Status
          debug:
            msg: |
              Domain already provisioned = {{ (domain_provisioned_check.found | default(0)) > 0 }}
        - name: Join the domain if not already done
          when: (force_reinstall | default(false) | bool) or (domain_provisioned_check.found | default(0)) == 0
          block:
            - name: Delete smb.conf
              shell: rm -f /etc/samba/smb.conf
            - name: Join the domain
              shell: |
                timeout 300 \
                samba-tool domain join ad.zam.haus dc \
                -U"administrator" --realm=ad.zam.haus --password={{ administrator_password|quote }}
              register: join_out
              ignore_errors: true
            - name: Debug join output
              debug:
                msg: |
                  stdout:
                  {{ join_out.stdout | default('No output') }}
                  ====
                  stderr:
                  {{ join_out.stderr | default('No output') }}
            - name: Fail if joining the domain failed
              fail:
                msg: "Joining the domain failed. See previous output."
              when: join_out.rc != 0
            - name: Install kerberos config
              copy:
                src: /var/lib/samba/private/krb5.conf
                dest: /etc/krb5.conf
                remote_src: yes
                force: yes
            - name: Start Samba-Ad-Dc Service
              service:
                name: samba-ad-dc
                state: started
            - name: Wait for Samba-Ad-Dc Service to be started
              wait_for:
                port: 389
                state: started
                delay: 0
                timeout: 5
            - name: Get domain info
              shell: "samba-tool domain info 127.0.0.1"
              register: domain_info_out
              ignore_errors: true
            - name: Debug domain info output
              debug:
                msg: |
                  stdout:
                  {{ domain_info_out.stdout }}
                  ====
                  stderr:
                  {{ domain_info_out.stderr }}
            - name: Fail if domain info failed
              fail:
                msg: "Getting domain info failed. See previous output."
              when: domain_info_out.rc != 0
        - name: Add dns record for ad.zam.haus
          shell: |
            samba-tool dns add -U='AD\Administrator' --password={{ administrator_password|quote }} ad001.srv.zam.haus ad.zam.haus ad.zam.haus A {{ (ansible_default_ipv4.address if 'docker' not in group_names else inventory_hostname) | quote }}
          register: add_dns_out
          changed_when: add_dns_out.rc == 0
          failed_when: add_dns_out.rc != 0 and ('WERR_DNS_ERROR_RECORD_ALREADY_EXISTS' not in add_dns_out.stderr)
        - name: Add dns record for <hostname>.ad.zam.haus
          when: "'docker' not in group_names"
          shell: |
            samba-tool dns add -U='AD\Administrator' --password={{ administrator_password|quote }} ad001.srv.zam.haus ad.zam.haus {{ inventory_hostname_short | quote }}.ad.zam.haus A {{ ansible_default_ipv4.address | quote }}
          register: add_dns_out2
          changed_when: add_dns_out.rc == 0
          failed_when: add_dns_out.rc != 0 and ('WERR_DNS_ERROR_RECORD_ALREADY_EXISTS' not in add_dns_out.stderr)
        - name: Wait for Samba-Ad-Dc Service to sync
          when: add_dns_out.changed or add_dns_out2.changed
          block:
            - name: Check if Samba-Ad-Dc Service is started
              wait_for:
                port: 389
                state: started
                delay: 0
                timeout: 5
            - name: Check replication status
              shell: "samba-tool drs showrepl {{ inventory_hostname | quote }}"
              register: drs_out_local
              ignore_errors: true
              until: drs_out_local.stdout is not search('failed')
              retries: 10
              delay: 1
              changed_when: false
            - name: Check replication status
              shell: "samba-tool drs showrepl {{ ansible_play_hosts_all[0] | quote }}"
              register: drs_out_dns_fsmo_master
              ignore_errors: true
              until: drs_out_dns_fsmo_master.stdout is not search('failed')
              retries: 10
              delay: 1
              changed_when: false
            - debug:
                msg: |
                  Replication Status:
                  ====
                  Local:
                  {{ drs_out_local.stdout | default('No output') }}
                  ====
                  Remote:
                  {{ drs_out_dns_fsmo_master.stdout | default('No output') }}
                  ====
                  drs_good_local={{ drs_out_local.stdout is not search('failed') }}
                  drs_good_remote={{ drs_out_dns_fsmo_master.stdout is not search('failed') }}
                  dns_good={{ drs_out_local.stdout is not search('failed') and drs_out_dns_fsmo_master.stdout is not search('failed') }}

            - name: Restart Samba-Ad-Dc Service to pick up the new DNS record
              service:
                name: samba-ad-dc
                state: restarted
            - name: Wait for Samba-Ad-Dc Service to be started
              wait_for:
                port: 389
                state: started
                delay: 0
                timeout: 5
        - name: Test the DNS
          test_ad_dns:
            adc_list: "{{ ansible_play_hosts_all }}"
            domain: "ad.zam.haus"
          register: dns_test_out
          retries: 5
          delay: 1
          until: dns_test_out.failed == false

        # samba-tool dns zonelist -U='AD\Administrator' --password='P@ssw0rd' ad.zam.haus
        # samba-tool dns query -U='AD\Administrator' --password='P@ssw0rd' ad.zam.haus ad.zam.haus ad.zam.haus A
        # samba-tool dns add -U='AD\Administrator' --password='P@ssw0rd' ad001.zam.haus ad.zam.haus ad.zam.haus A 10.5.0.3
        # samba-tool drs showrepl ad001.srv.zam.haus

    - name: Set samba settings
      block:
        - name: Insert block in [global] section
          ansible.builtin.blockinfile:
            path: /etc/samba/smb.conf
            block: |
              max log size = 10000
              log level = 3 auth_audit:3 auth_json_audit:3 dsdb_json_audit:5 dsdb_password_json_audit:5 dsdb_group_json_audit:5 dsdb_transaction_json_audit:5
            marker: "# {mark} ANSIBLE MANAGED BLOCK [global]"
            insertafter: '^\[global\]'
          register: set_samba_settings_global_out
        - name: Restart Samba-Ad-Dc Service to pick up the new settings
          when: set_samba_settings_global_out.changed
          service:
            name: samba-ad-dc
            state: restarted
        - name: Wait for Samba-Ad-Dc Service to be started
          when: set_samba_settings_global_out.changed
          wait_for:
            port: 389
            state: started
            delay: 0
            timeout: 5

    - name: Relax password policy
      block:
        - name: Set password policy
          shell: |
            samba-tool domain passwordsettings pso create UsersPSO 100 --max-pwd-age=36500
          register: set_password_policy_out
          ignore_errors: true
          changed_when: set_password_policy_out.rc == 0 and 'PSO successfully created' in set_password_policy_out.stderr
          failed_when: set_password_polcy_out.rc != 0 and 'already exists' not in set_password_policy_out.stderr and 'PSO successfully created' not in set_password_policy_out.stderr
        - name: Apply password policy to Users group
          shell: |
            samba-tool domain passwordsettings pso apply UsersPSO Users
          register: apply_password_policy_out
          ignore_errors: true
          changed_when: apply_password_policy_out.rc == 0 and 'applied to' in apply_password_policy_out.stderr
          failed_when: apply_password_policy_out.rc != 0 and 'already applies' not in apply_password_policy_out.stderr and 'applied to' not in apply_password_policy_out.stderr

    - name: Enable samba-ad-dc service at boot
      service:
        name: samba-ad-dc
        enabled: yes

    - name: Install and configure NTP
      tags: [ntp]
      when: inventory_hostname == ansible_play_hosts_all[0]
      block:
        - name: Install ntpd
          apt:
            pkg:
              - ntpsec

        - name: configure ntpd
          template:
            src: templates/ntp.conf.j2
            dest: /etc/ntpsec/ntp.conf
            mode: '0644'
            owner: root
            group: root

        - name: Give access to sign socket
          shell: |
            chgrp ntpsec /var/lib/samba/ntp_signd
            chmod g+rx /var/lib/samba/ntp_signd
          ignore_errors: true
          failed_when: false

        - name: Restart ntpd
          service:
            name: ntpsec
            state: restarted
            enabled: yes

        # TODO does not work in prod, and cannot be tested in docker due to missing systemd.
        #- name: Wait for ntpd to be started
        #  wait_for:
        #    port: 123
        #    state: started
        #    delay: 0
        #    timeout: 10
        #  ignore_errors: "{{ 'docker' in group_names }}"

        - name: Start daemon manually when in docker and when necessary
          when: "'docker' in group_names"
          shell: |
            pgrep ntpd || ntpd -gu ntpsec:ntpsec -c /etc/ntpsec/ntp.conf
          register: start_ntpd_out
          changed_when: start_ntpd_out.rc == 0
          failed_when: start_ntpd_out.rc != 0 and 'already running' not in start_ntpd_out.stderr
        # ntpq -pn
        # ntpmon localhost

    - name: Test shares, LDAP and kerberos
      block:
        - name: Test share with machine password
          shell: |
            smbclient -L {{ inventory_hostname | quote }} -P
          changed_when: false
        - name: Test share with admin password
          args:
            executable: /bin/bash
          shell: |
            set -euxo pipefail
            smbclient -L {{ inventory_hostname | quote }} -U 'AD\Administrator' --password {{ administrator_password|quote }}
            smbclient -L {{ inventory_hostname | quote }} -U 'AD\Administrator' --password {{ administrator_password|quote }} | grep IPC
            smbclient -L {{ inventory_hostname | quote }} -U 'AD\Administrator' --password {{ administrator_password|quote }} | grep sysvol
            smbclient -L {{ inventory_hostname | quote }} -U 'AD\Administrator' --password {{ administrator_password|quote }} | grep netlogon
          changed_when: false
        - name: Test LDAP with admin password
          args:
            executable: /bin/bash
          shell: |
            set -euxo pipefail
            ldbsearch -H ldap://ad.zam.haus "cn=administrator" -U AD\\Administrator --password {{ administrator_password|quote }} \
                | grep "memberOf: CN=Domain Admins,CN=Users,DC=ad,DC=zam,DC=haus"
          changed_when: false
        - name: Test kerberos
          # This does not work with --use-kerberos=required in Debian / with smbclient 4.22. It works with --use-kerberos=desired. Ubuntu supports both with smbclient 4.19.
          block:
            - name : Get kerberos ticket
              args:
                executable: /bin/bash
              shell: |
                set -euxo pipefail
                kinit --password-file=<(echo {{ administrator_password|quote }}) Administrator@ad.zam.haus
                klist
                smbclient -L {{ inventory_hostname|quote }}.ad.zam.haus --use-kerberos desired -N
              changed_when: false
          always:
            - name: Destroy kerberos ticket
              shell: kdestroy
              ignore_errors: true
              changed_when: false


























